// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AutoFeed_Backend_DAO.Models;

public partial class Schedule
{
    public int SchedId { get; set; }

    public int? UserId { get; set; }

    public int? TaskId { get; set; }

    public int? CbarnId { get; set; }

    public string Description { get; set; }

    public bool? Status { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public DateTime? CreatedDate { get; set; }

    public virtual ChickenBarn Cbarn { get; set; }

    public virtual Task Task { get; set; }

    public virtual User User { get; set; }
}