// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;

namespace AutoFeed_Backend_DAO.Models;

public partial class AutoFeedDBContext : DbContext
{
    public AutoFeedDBContext()
    {
    }

    public AutoFeedDBContext(DbContextOptions<AutoFeedDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Barn> Barns { get; set; }

    public virtual DbSet<BarnIoTDevice> BarnIoTDevices { get; set; }

    public virtual DbSet<ChickenBarn> ChickenBarns { get; set; }

    public virtual DbSet<DataIoT> DataIoTs { get; set; }

    public virtual DbSet<FeedingRule> FeedingRules { get; set; }

    public virtual DbSet<FeedingRuleDetail> FeedingRuleDetails { get; set; }

    public virtual DbSet<FlockChicken> FlockChickens { get; set; }

    public virtual DbSet<Food> Foods { get; set; }

    public virtual DbSet<FoodStorage> FoodStorages { get; set; }

    public virtual DbSet<Inventory> Inventories { get; set; }

    public virtual DbSet<IoTDevice> IoTDevices { get; set; }

    public virtual DbSet<LargeChicken> LargeChickens { get; set; }

    public virtual DbSet<Report> Reports { get; set; }

    public virtual DbSet<Request> Requests { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<Schedule> Schedules { get; set; }

    public virtual DbSet<Task> Tasks { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(GetConnectionString("DefaultConnection")).UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);


    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Barn>(entity =>
        {
            entity.HasKey(e => e.BarnId).HasName("PK__Barn__C683E3D4B5A9DA79");

            entity.ToTable("Barn");

            entity.Property(e => e.BarnId).HasColumnName("barnID");
            entity.Property(e => e.Area)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("area");
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createDate");
            entity.Property(e => e.Humidity)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("humidity");
            entity.Property(e => e.Temperature)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("temperature");
            entity.Property(e => e.Type)
                .HasMaxLength(50)
                .HasColumnName("type");
        });

        modelBuilder.Entity<BarnIoTDevice>(entity =>
        {
            entity.HasKey(e => e.BDeviceId).HasName("PK__BarnIoT___9C4A5818C639A0C6");

            entity.ToTable("BarnIoT_Device");

            entity.Property(e => e.BDeviceId).HasColumnName("bDeviceID");
            entity.Property(e => e.BarnId).HasColumnName("barnID");
            entity.Property(e => e.DeviceId).HasColumnName("deviceID");
            entity.Property(e => e.InstallationDate).HasColumnName("installationDate");
            entity.Property(e => e.Status)
                .HasDefaultValue(true)
                .HasColumnName("status");

            entity.HasOne(d => d.Barn).WithMany(p => p.BarnIoTDevices)
                .HasForeignKey(d => d.BarnId)
                .HasConstraintName("FK_BarnIoT_Barn");

            entity.HasOne(d => d.Device).WithMany(p => p.BarnIoTDevices)
                .HasForeignKey(d => d.DeviceId)
                .HasConstraintName("FK_BarnIoT_Device");
        });

        modelBuilder.Entity<ChickenBarn>(entity =>
        {
            entity.HasKey(e => e.CbarnId).HasName("PK__ChickenB__2D4B3D06C6913E6B");

            entity.ToTable("ChickenBarn");

            entity.HasIndex(e => e.FlockId, "UQ__ChickenB__6D32C9F01F710A05").IsUnique();

            entity.HasIndex(e => e.ChickenLid, "UQ__ChickenB__6DE57F4A867962DF").IsUnique();

            entity.Property(e => e.CbarnId).HasColumnName("CBarnID");
            entity.Property(e => e.BarnId).HasColumnName("barnID");
            entity.Property(e => e.ChickenLid).HasColumnName("chickenLID");
            entity.Property(e => e.ExportDate).HasColumnName("exportDate");
            entity.Property(e => e.FlockId).HasColumnName("flockID");
            entity.Property(e => e.Note).HasColumnName("note");
            entity.Property(e => e.StartDate).HasColumnName("startDate");
            entity.Property(e => e.Status)
                .HasDefaultValue(true)
                .HasColumnName("status");

            entity.HasOne(d => d.Barn).WithMany(p => p.ChickenBarns)
                .HasForeignKey(d => d.BarnId)
                .HasConstraintName("FK_CBarn_Barn");

            entity.HasOne(d => d.ChickenL).WithOne(p => p.ChickenBarn)
                .HasForeignKey<ChickenBarn>(d => d.ChickenLid)
                .HasConstraintName("FK_CBarn_LargeChicken");

            entity.HasOne(d => d.Flock).WithOne(p => p.ChickenBarn)
                .HasForeignKey<ChickenBarn>(d => d.FlockId)
                .HasConstraintName("FK_CBarn_Flock");
        });

        modelBuilder.Entity<DataIoT>(entity =>
        {
            entity.HasKey(e => e.DataId).HasName("PK__Data_IoT__923E3685ED6185B8");

            entity.ToTable("Data_IoT");

            entity.Property(e => e.DataId).HasColumnName("dataID");
            entity.Property(e => e.BarnId).HasColumnName("barnID");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.DeviceId).HasColumnName("deviceID");
            entity.Property(e => e.RecordDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("recordDate");
            entity.Property(e => e.SequenceNumber).HasColumnName("sequenceNumber");
            entity.Property(e => e.Value)
                .HasColumnType("decimal(18, 4)")
                .HasColumnName("value");

            entity.HasOne(d => d.Barn).WithMany(p => p.DataIoTs)
                .HasForeignKey(d => d.BarnId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DataIoT_Barn");

            entity.HasOne(d => d.Device).WithMany(p => p.DataIoTs)
                .HasForeignKey(d => d.DeviceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DataIoT_Device");
        });

        modelBuilder.Entity<FeedingRule>(entity =>
        {
            entity.HasKey(e => e.RuleId).HasName("PK__FeedingR__121C064143CA6C66");

            entity.ToTable("FeedingRule");

            entity.HasIndex(e => e.FlockId, "UQ__FeedingR__6D32C9F0ACA93721").IsUnique();

            entity.HasIndex(e => e.ChickenLid, "UQ__FeedingR__6DE57F4A528CA489").IsUnique();

            entity.Property(e => e.RuleId).HasColumnName("ruleID");
            entity.Property(e => e.ChickenLid).HasColumnName("chickenLID");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.FlockId).HasColumnName("flockID");
            entity.Property(e => e.Note).HasColumnName("note");
            entity.Property(e => e.Times).HasColumnName("times");

            entity.HasOne(d => d.ChickenL).WithOne(p => p.FeedingRule)
                .HasForeignKey<FeedingRule>(d => d.ChickenLid)
                .HasConstraintName("FK_Rule_LargeChicken");

            entity.HasOne(d => d.Flock).WithOne(p => p.FeedingRule)
                .HasForeignKey<FeedingRule>(d => d.FlockId)
                .HasConstraintName("FK_Rule_Flock");
        });

        modelBuilder.Entity<FeedingRuleDetail>(entity =>
        {
            entity.HasKey(e => e.FeedRuleDetailId).HasName("PK__FeedingR__26A980CACF643DEE");

            entity.ToTable("FeedingRuleDetail");

            entity.Property(e => e.FeedRuleDetailId).HasColumnName("feedRuleDetailID");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.EndDate).HasColumnName("endDate");
            entity.Property(e => e.FoodId).HasColumnName("foodID");
            entity.Property(e => e.RuleId).HasColumnName("ruleID");
            entity.Property(e => e.StartDate).HasColumnName("startDate");
            entity.Property(e => e.Status)
                .HasDefaultValue(true)
                .HasColumnName("status");

            entity.HasOne(d => d.Food).WithMany(p => p.FeedingRuleDetails)
                .HasForeignKey(d => d.FoodId)
                .HasConstraintName("FK_Detail_Food");

            entity.HasOne(d => d.Rule).WithMany(p => p.FeedingRuleDetails)
                .HasForeignKey(d => d.RuleId)
                .HasConstraintName("FK_Detail_Rule");
        });

        modelBuilder.Entity<FlockChicken>(entity =>
        {
            entity.HasKey(e => e.FlockId).HasName("PK__FlockChi__6D32C9F18A5C407A");

            entity.ToTable("FlockChicken");

            entity.Property(e => e.FlockId).HasColumnName("flockID");
            entity.Property(e => e.Age).HasColumnName("age");
            entity.Property(e => e.HealthStatus)
                .HasMaxLength(100)
                .HasColumnName("healthStatus");
            entity.Property(e => e.Name)
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.Note).HasColumnName("note");
            entity.Property(e => e.Quantity).HasColumnName("quantity");
            entity.Property(e => e.Weight)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("weight");
        });

        modelBuilder.Entity<Food>(entity =>
        {
            entity.HasKey(e => e.FoodId).HasName("PK__Food__77EAEA19DA26AB9E");

            entity.ToTable("Food");

            entity.Property(e => e.FoodId).HasColumnName("foodID");
            entity.Property(e => e.Name)
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.Note).HasColumnName("note");
            entity.Property(e => e.Price)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("price");
            entity.Property(e => e.Quantity).HasColumnName("quantity");
            entity.Property(e => e.Type)
                .HasMaxLength(50)
                .HasColumnName("type");
        });

        modelBuilder.Entity<FoodStorage>(entity =>
        {
            entity.HasKey(e => e.StorageId).HasName("PK__FoodStor__D1437C8A8FDB9563");

            entity.ToTable("FoodStorage");

            entity.Property(e => e.StorageId).HasColumnName("storageID");
            entity.Property(e => e.BarnId).HasColumnName("barnID");
            entity.Property(e => e.FoodId).HasColumnName("foodID");
            entity.Property(e => e.FoodWeight)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("food_weight");
            entity.Property(e => e.LeftoverFood)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("leftover_food");
            entity.Property(e => e.Note).HasColumnName("note");

            entity.HasOne(d => d.Barn).WithMany(p => p.FoodStorages)
                .HasForeignKey(d => d.BarnId)
                .HasConstraintName("FK_Storage_Barn");

            entity.HasOne(d => d.Food).WithMany(p => p.FoodStorages)
                .HasForeignKey(d => d.FoodId)
                .HasConstraintName("FK_Storage_Food");
        });

        modelBuilder.Entity<Inventory>(entity =>
        {
            entity.HasKey(e => e.InventId).HasName("PK__Inventor__3805E39F00A50E28");

            entity.ToTable("Inventory");

            entity.Property(e => e.InventId).HasColumnName("inventID");
            entity.Property(e => e.ExpiredDate).HasColumnName("expiredDate");
            entity.Property(e => e.FoodId).HasColumnName("foodID");
            entity.Property(e => e.Quantity).HasColumnName("quantity");
            entity.Property(e => e.WeightPerBag)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("weightPerBag");

            entity.HasOne(d => d.Food).WithMany(p => p.Inventories)
                .HasForeignKey(d => d.FoodId)
                .HasConstraintName("FK_Inventory_Food");
        });

        modelBuilder.Entity<IoTDevice>(entity =>
        {
            entity.HasKey(e => e.DeviceId).HasName("PK__IoT_Devi__84BE14B7979A2D2E");

            entity.ToTable("IoT_Device");

            entity.Property(e => e.DeviceId).HasColumnName("deviceID");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.Name)
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.Status)
                .HasDefaultValue(true)
                .HasColumnName("status");
        });

        modelBuilder.Entity<LargeChicken>(entity =>
        {
            entity.HasKey(e => e.ChickenLid).HasName("PK__LargeChi__6DE57F4BDAD1FD67");

            entity.ToTable("LargeChicken");

            entity.Property(e => e.ChickenLid).HasColumnName("chickenLID");
            entity.Property(e => e.Age).HasColumnName("age");
            entity.Property(e => e.FlockId).HasColumnName("flockID");
            entity.Property(e => e.HealthStatus)
                .HasMaxLength(100)
                .HasColumnName("healthStatus");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("isActive");
            entity.Property(e => e.Name)
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.Note).HasColumnName("note");
            entity.Property(e => e.Weight)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("weight");

            entity.HasOne(d => d.Flock).WithMany(p => p.LargeChickens)
                .HasForeignKey(d => d.FlockId)
                .HasConstraintName("FK_LargeChicken_Flock");
        });

        modelBuilder.Entity<Report>(entity =>
        {
            entity.HasKey(e => e.ReportId).HasName("PK__Report__1C9B4ECDBE34E441");

            entity.ToTable("Report");

            entity.Property(e => e.ReportId).HasColumnName("reportID");
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createDate");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.Status)
                .HasDefaultValue(true)
                .HasColumnName("status");
            entity.Property(e => e.Type)
                .HasMaxLength(50)
                .HasColumnName("type");
            entity.Property(e => e.UserId).HasColumnName("userID");

            entity.HasOne(d => d.User).WithMany(p => p.Reports)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_Report_User");
        });

        modelBuilder.Entity<Request>(entity =>
        {
            entity.HasKey(e => e.RequestId).HasName("PK__Request__E3C5DE5189D7E9A8");

            entity.ToTable("Request");

            entity.Property(e => e.RequestId).HasColumnName("requestID");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.Status)
                .HasDefaultValue(false)
                .HasColumnName("status");
            entity.Property(e => e.Type)
                .HasMaxLength(50)
                .HasColumnName("type");
            entity.Property(e => e.UserId).HasColumnName("userID");

            entity.HasOne(d => d.User).WithMany(p => p.Requests)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_Request_User");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK__Role__CD98460A7592B319");

            entity.ToTable("Role");

            entity.Property(e => e.RoleId).HasColumnName("roleID");
            entity.Property(e => e.Description)
                .HasMaxLength(255)
                .HasColumnName("description");
        });

        modelBuilder.Entity<Schedule>(entity =>
        {
            entity.HasKey(e => e.SchedId).HasName("PK__Schedule__F378328E77F1BDC1");

            entity.ToTable("Schedule");

            entity.Property(e => e.SchedId).HasColumnName("schedID");
            entity.Property(e => e.CbarnId).HasColumnName("CBarnID");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createdDate");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.EndDate)
                .HasColumnType("datetime")
                .HasColumnName("endDate");
            entity.Property(e => e.StartDate)
                .HasColumnType("datetime")
                .HasColumnName("startDate");
            entity.Property(e => e.Status)
                .HasDefaultValue(false)
                .HasColumnName("status");
            entity.Property(e => e.TaskId).HasColumnName("taskID");
            entity.Property(e => e.UserId).HasColumnName("userID");

            entity.HasOne(d => d.Cbarn).WithMany(p => p.Schedules)
                .HasForeignKey(d => d.CbarnId)
                .HasConstraintName("FK_Sched_CBarn");

            entity.HasOne(d => d.Task).WithMany(p => p.Schedules)
                .HasForeignKey(d => d.TaskId)
                .HasConstraintName("FK_Sched_Task");

            entity.HasOne(d => d.User).WithMany(p => p.Schedules)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_Sched_User");
        });

        modelBuilder.Entity<Task>(entity =>
        {
            entity.HasKey(e => e.TaskId).HasName("PK__Task__DD5D55A2A729556E");

            entity.ToTable("Task");

            entity.Property(e => e.TaskId).HasColumnName("taskID");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.Status)
                .HasDefaultValue(false)
                .HasColumnName("status");
            entity.Property(e => e.Title)
                .HasMaxLength(100)
                .HasColumnName("title");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__User__CB9A1CDF7E6936EC");

            entity.ToTable("User");

            entity.HasIndex(e => e.Email, "UQ__User__AB6E6164C1126FE1").IsUnique();

            entity.HasIndex(e => e.Username, "UQ__User__F3DBC572CFDF989E").IsUnique();

            entity.Property(e => e.UserId).HasColumnName("userID");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("email");
            entity.Property(e => e.FullName)
                .HasMaxLength(100)
                .HasColumnName("fullName");
            entity.Property(e => e.LastLogin)
                .HasColumnType("datetime")
                .HasColumnName("lastLogin");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("password");
            entity.Property(e => e.Phone)
                .HasMaxLength(20)
                .HasColumnName("phone");
            entity.Property(e => e.RoleId).HasColumnName("roleID");
            entity.Property(e => e.Status)
                .HasDefaultValue(true)
                .HasColumnName("status");
            entity.Property(e => e.Username)
                .HasMaxLength(50)
                .HasColumnName("username");

            entity.HasOne(d => d.Role).WithMany(p => p.Users)
                .HasForeignKey(d => d.RoleId)
                .HasConstraintName("FK_User_Role");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}