// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AutoFeed_Backend_DAO.Models;

public partial class Barn
{
    public int BarnId { get; set; }

    public decimal? Temperature { get; set; }

    public decimal? Humidity { get; set; }

    public string Type { get; set; }

    public decimal? Area { get; set; }

    public bool Status { get; set; }

    public DateTime? CreateDate { get; set; }

    public virtual ICollection<BarnIoTDevice> BarnIoTDevices { get; set; } = new List<BarnIoTDevice>();

    public virtual ICollection<ChickenBarn> ChickenBarns { get; set; } = new List<ChickenBarn>();

    public virtual ICollection<DataIoT> DataIoTs { get; set; } = new List<DataIoT>();

    public virtual ICollection<FoodStorage> FoodStorages { get; set; } = new List<FoodStorage>();
}