// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AutoFeed_Backend_DAO.Models;

public partial class BarnIoTDevice
{
    public int BDeviceId { get; set; }

    public int? BarnId { get; set; }

    public int? DeviceId { get; set; }

    public DateOnly? InstallationDate { get; set; }

    public bool? Status { get; set; }

    public virtual Barn Barn { get; set; }

    public virtual IoTDevice Device { get; set; }
}