// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AutoFeed_Backend_DAO.Models;

public partial class ChickenBarn
{
    public int CbarnId { get; set; }

    public int? BarnId { get; set; }

    public int? ChickenLid { get; set; }

    public int? FlockId { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? ExportDate { get; set; }

    public string Note { get; set; }

    public bool? Status { get; set; }

    public virtual Barn Barn { get; set; }

    public virtual LargeChicken ChickenL { get; set; }

    public virtual FlockChicken Flock { get; set; }

    public virtual ICollection<Schedule> Schedules { get; set; } = new List<Schedule>();
}