// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AutoFeed_Backend_DAO.Models;

public partial class FeedingRuleDetail
{
    public int FeedRuleDetailId { get; set; }

    public int? RuleId { get; set; }

    public int? FoodId { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public string Description { get; set; }

    public bool? Status { get; set; }

    public virtual Food Food { get; set; }

    public virtual FeedingRule Rule { get; set; }
}