// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AutoFeed_Backend_DAO.Models;

public partial class IoTDevice
{
    public int DeviceId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public bool? Status { get; set; }

    public virtual ICollection<BarnIoTDevice> BarnIoTDevices { get; set; } = new List<BarnIoTDevice>();

    public virtual ICollection<DataIoT> DataIoTs { get; set; } = new List<DataIoT>();
}