// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AutoFeed_Backend_DAO.Models;

public partial class Report
{
    public int ReportId { get; set; }

    public int? UserId { get; set; }

    public string Type { get; set; }

    public string Description { get; set; }

    public bool? Status { get; set; }

    public DateTime? CreateDate { get; set; }

    public virtual User User { get; set; }
}